{% set name = "ocaml-findlib" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.camlcity.org/download/findlib-{{ version }}.tar.gz
  sha256: 20fecdbfc0cc8c8f3779e81f1fb91a2c5eaff421037679d4c64ab14a32e8f2ee

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - m4
  host:
    - ocaml
  run:
    - ocaml

test:
  commands:
    - ocamlfind install -help

about:
  home: http://projects.camlcity.org/projects/findlib.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: opam is a source-based package manager for OCaml
  doc_url: http://projects.camlcity.org/projects/dl/findlib-{{ version }}/doc/guide-html/index.html
  dev_url: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - isuruf
    - slel
