{% set name = "ocaml-findlib" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.camlcity.org/download/findlib-{{ version }}.tar.gz
  sha256: 8e85cfa57e8745715432df3116697c8f41cb24b5ec16d1d5acd25e0196d34303

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - m4
    - make
  host:
    - ocaml
    - ocamlbuild
  run:
    - ocaml

test:
  commands:
    - ocamlfind install -help

about:
  home: http://projects.camlcity.org/projects/findlib.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'opam is a source-based package manager for OCaml'
  doc_url: http://projects.camlcity.org/projects/dl/findlib-{{ version }}/doc/guide-html/index.html
  dev_url: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - isuruf
    - slel
