{% set name = "ocaml-findlib" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.camlcity.org/download/findlib-{{ version }}.tar.gz
  sha256: c310fcb62838d9e50f0b6d6c5ceefcbe4fe056f72496950ae7d5c6cdaae2cc41

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - m4
  host:
    - ocaml
  run:
    - ocaml

test:
  commands:
    - ocamlfind install -help

about:
  home: http://projects.camlcity.org/projects/findlib.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: opam is a source-based package manager for OCaml
  doc_url: http://projects.camlcity.org/projects/dl/findlib-{{ version }}/doc/guide-html/index.html
  dev_url: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - isuruf
    - slel
