{% set name = "ocaml-findlib" %}
{% set version = "1.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.camlcity.org/download/findlib-{{ version }}.tar.gz
  sha256: 662c910f774e9fee3a19c4e057f380581ab2fc4ee52da4761304ac9c31b8869d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - m4
    - make
  host:
    - ocaml
    - ocamlbuild
  run:
    - ocaml

test:
  commands:
    - ocamlfind install -help

about:
  home: http://projects.camlcity.org/projects/findlib.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'opam is a source-based package manager for OCaml'
  doc_url: http://projects.camlcity.org/projects/dl/findlib-{{ version }}/doc/guide-html/index.html
  dev_url: https://github.com/ocaml/opam

extra:
  recipe-maintainers:
    - isuruf
    - slel
