travis:
  secure:
    BINSTAR_TOKEN: Gn14p7frqapXUUKUwo3YbzzAZRGD5TXleOhn/8JAbGy0U1aS6kKthW09cdXbClGjJl6udw8J4r8GpEN1J2tuEWGrT1Uk8hGEsrx/jATta/eC8ZOEgK9yTky26P8cDow1WDvI9YmEBXlmxNzsTIrKZwigzoAi8ZDGX2ZGeKh2IT7to5ItssrsTZkC9HeHqVluU5zW/QLA8SuSUzOb/Wb3dcyKb1JNrUI1mpN4SOgm+w9w6fCOiqEF0OurdjDSrFKJ4PFyKPKjUK/dfc8y4I432Tmjmr2oobt5+8Ew3RNLTHQ4NOBTiJKYkhVUbrQys+8h/qDBPkSjHZFj+9XkjZmVo8FfZOCXGfhiBs0Y6Uf3rYQ7qrUVnIGiPF+2o5568nf3xBOglJrnvN5emsm8dGnqODw9zjFN9mmFIVCVFERef1PuBXa2H5hC8ZvvxSkAIIq5jV7JZdBgQTkDzCNBDmh8qah+RCWhqe8WaJzpOcG9oPK0p26ryMTXXxjzyxhdlFUZ9TQvA5/mtoscDEGJJJSpJskjq8E91jONYx3n4thMgzOoK4kp2YxJe5pNFxar5oacZV3BZWA5fZexezjc8ZO0Y0E05V6sx/vEfGveKubOKZWLFiAPsSQo3NyV3WBuS2rgSR09gfq3/7PS3NNcEieU5ktG9MRckMQye1HvqM3qAGI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
